apiVersion: batch/v1
kind: Job
metadata:
 name: musae
spec:
 template:
  spec:
   priorityClassName: research-low
   containers:
    - name: musae-container
      image: ls6-stud-registry.informatik.uni-wuerzburg.de/studtodorkov/seminar
      imagePullPolicy: "Always"
      resources:
       limits:
        cpu: "12"
        memory: "60Gi"
        nvidia.com/gpu: "1"
       requests:
        cpu: "12"
        memory: "60Gi"
        nvidia.com/gpu: "1"
      command: ["python3", "-u", "/repo/src/init.py"]
      volumeMounts:
       - mountPath: /repo
         name: repo
       - mountPath: /dev/shm
         name: dshm
   imagePullSecrets:
    - name: lsx-registry
   restartPolicy: "Never"
   volumes:
    - name: repo
      cephfs:
       monitors:
        - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
       user: studtodorkov
       path: "/home/stud/todorkov/sem_musik_ki/"
       secretRef:
        name: ceph-secret
    - name: dshm
      emptyDir:
       medium: "Memory"
       sizeLimit: "2Gi"
